### ISSUE TITLE
compress & decompress should throw a normal exception instead of fail

### ISSUE THREAD

**Issue by jchia** [alphaHeavy/lzma-conduit#11]
When an error is encountered, such as bad input file format, the functions use `Monad` `fail` instead of throwing an exception that can be caught. This ultimately results in an `ErrorCall`.

Error-wise, I think `compress` and `decompress` should have behavior similar to file reading, throwing `IOException` when errors are encountered. `IOException` is something that can be reasonably caught. `ErrorCall` isn't. I think this is what `Data.Conduit.Zlib` does when using `IO` as the base monad. `compress` and `decompress` already has the `MonadResource m` constraint, with implies a `MonadIO m` constraint, so we can always `throwIO` instead of `fail`.

**Comment by NathanHowell** [comment]
PR #12 merged.
