### ISSUE TITLE
compress [] and compress [""] should have the same behavior

### ISSUE THREAD

**Issue by jchia** [alphaHeavy/lzma-conduit#13]
Giving nothing to `compress` causes it to `yield` nothing at all  but giving an empty `ByteString` to `compress` causes it to `yield` some non-empty `ByteString`.

Trying to decompress an empty file with unxz results in an error. Accordingly, I think `compress` should behave the same whether it's given nothing or an empty `ByteString`.

Incidentally, the current behavior is causing `prop_decompressCorrupt` to encounter a failure not because of compressed data corruption but because `header'` is empty; the test passes not because decompress detects input corruption.

**Comment by NathanHowell** [comment]
This sounds broken, the behavior here should match xz/unxz. Have you looked into how complex the fix is?
