### ISSUE TITLE
New hackage version

### ISSUE THREAD

**Issue by jchia** [alphaHeavy/lzma-conduit#15]
There hasn't been many changes since my bug fix commit d47bf97938fd4b318e3d1044cc5b084bf07fedc0, although it's been a few months. Would you mind uploading a new hackage version so that I can directly use the latest version from stackage?

**Comment by NathanHowell** [comment]
Totally spaced, sorry about that... https://hackage.haskell.org/package/lzma-conduit-1.1.3.2

**Comment by jchia** [comment]
Thanks
