### ISSUE TITLE
resourcet-1.3 not accepted

### ISSUE THREAD

**Issue by ysangkok** [alphaHeavy/lzma-conduit#23]
This series should be accepted for the package to remain in Stackage after

* https://github.com/commercialhaskell/stackage/issues/6744

**Comment by jchia** [comment]
#24

**Comment by ysangkok** [comment]
Closing since this project seems abandoned.

**Comment by luispedro** [comment]
Self-plug, but you can use my `conduit-algorithms` which now incorporates updated code from this package: https://www.stackage.org/haddock/nightly-2024-05-01/conduit-algorithms-0.0.14.0/Data-Conduit-Lzma2.html
