### ISSUE TITLE
consider implementing lzma-conduit in terms of `lzma`

### ISSUE THREAD

**Issue by hvr** [alphaHeavy/lzma-conduit#8]
I designed http://hackage.haskell.org/package/lzma to be a streaming-api agnostic common denominator low/mid-level binding to `liblzma`, and it works quite well for lazy-bytestrings, io-streams, and pipes (and also takes care of lzma on windows); So I'd wonder if it would make sense for `lzma-conduit` to build on top of `lzma` too...

**Comment by NathanHowell** [comment]
Sounds like a good idea, definitely open to taking on such a dependency. Have you looked into how much work it would be to make this happen?

**Comment by hvr** [comment]
Shouldn't be much work if we can drop the `Bindings.Lzma` module.

The `Data.Conduit.Lzma` API should be easy to retain as-is, while you may want to add variants which allow to set parameters in the style of e.g. http://hackage.haskell.org/package/pipes-lzma-0.1.1.0/docs/Pipes-Lzma.html

If `conduit`'s api is similiar enough to the `pipes` api, then http://hackage.haskell.org/package/pipes-lzma-0.1.1.0/docs/src/Pipes-Lzma.html should give a good idea of the (little) work needed...

**Comment by hvr** [comment]
@NathanHowell I finally got around to implement this myself, see #16

**Comment by NathanHowell** [comment]
Thanks, sorry for the delay in getting this merged 👍

**Comment by hvr** [comment]
@NathanHowell btw, I asked this somewhere else already: It's just a matter of exporting the '*With' functions, and reexporting the parameter data-structures as was done in

https://hackage.haskell.org/package/pipes-lzma-0.1.1.2/docs/Pipes-Lzma.html

and you'd get a richer API with little effort.

If you want that, I can create a new PR

**Comment by NathanHowell** [comment]
Yes please, go for it 👍
